---
ytitle: "yuhanwork"
output: html_document
date: "2023-07-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library("Hmisc")
library("PerformanceAnalytics")
library(rstanarm)
library(gam)
library(flexplot)
```



```{r}
rawdata <- read_excel("data/USGS_Aggregates_Data-1971-2021.xlsx", sheet = "Complete_1971_2021")

```

```{r}
rawdata |>
  summarise(project_total = n(), .by = Region) |>
  ggplot(aes(x = Region, y = project_total, fill = Region)) + 
  geom_col()


rawdata |>
  summarise(project_total = n(), .by = Division) |>
  ggplot(aes(x = Division, y = project_total)) + 
  geom_col()

```

Goal: 

X axis: South, West, East, Middle East.....
Y axis: Total number of construction/projects in that region for all years

# Correlation Analysis

```{r}

#Import Datasets + Innitial Manipulation
setwd("~/Desktop/Rdata-science/cementresearch")
datacpi <- read_csv("data/cpi.csv") |>
   pivot_longer(cols = `1960`:`2022`, 
               names_to = "years",
               values_to = "cpi") |>
  select(c(`Country Name`, years, cpi)) |>
  filter(`Country Name` == "United States") |>
  filter(years >= 1998 & years < 2021)

dataunemploy <- read_csv("data/unemploy.csv") |>
   pivot_longer(cols = `1960`:`2022`, 
               names_to = "years",
               values_to = "unemploy") |>
  select(c(`Country Name`, years, unemploy)) |>
  filter(`Country Name` == "United States") |>
  drop_na() |>
  filter(years >= 1998 & years < 2021)

datagdp <- read_csv("data/gdpall.csv") |>
   pivot_longer(cols = `1960`:`2022`, 
               names_to = "years",
               values_to = "gdp") |>
  select(c(`Country Name`, years, gdp)) |>
  filter(`Country Name` == "United States") |>
  drop_na() |>
  filter(years >= 1998 & years < 2021)

dataoil <- read_csv("data/oil.csv") |>
  filter(!DCOILWTICO == ".") |>
  mutate(oilprice = as.double(DCOILWTICO)) |>
  mutate(year = as.double(str_sub(DATE, 0,4))) |>
  summarise(oilprice = mean(oilprice), .by = year) |>
  filter(year >= 1998 & year < 2021)

datacement <- read_csv("data/cement.csv") |>
  filter(!PCU32733132733106 == ".") |>
  mutate(cementppi = as.double(PCU32733132733106)) |>
  mutate(year = as.double(str_sub(DATE, 0,4))) |>
  summarise(cementppi = mean(cementppi), .by = year) |>
  filter(year >= 1998 & year < 2021)

popdata <- read.csv("data/POPTHM.csv") |>
  filter(!POPTHM == ".") |>
  mutate(population = as.double(POPTHM)) |>
  mutate(year = as.double(str_sub(DATE, 0,4))) |>
  summarise(population = mean(population), .by = year) |>
  filter(year >= 1998 & year < 2021) 

cementprod <- read.csv("data/IPG3273S.csv") |>
  filter(!IPG3273S == ".") |>
  mutate(concreteid = as.double(IPG3273S)) |>
  mutate(year = as.double(str_sub(DATE, 0,4))) |>
  summarise(concreteid = mean(concreteid), .by = year) |>
  filter(year >= 1998 & year < 2021) 

cementclinker <- read.csv("data/cementclinker.csv") |>
  mutate(Cement = as.double(str_remove(Cement, ","))) |>
  mutate(Clinker = as.double(str_remove(Clinker, ","))) 

housingcomplete <- read.csv("data/housingunit.csv") |>
  mutate(year = `X1968`, housing = as.double(str_remove(`X1.319.80`, ","))) |>
  filter(year >= 1998 & year < 2021) |>
  select(year, housing)

setwd("~/Desktop/Rdata-science/cementresearch")
constructspending <- read.csv("data/construct.csv") |>
  mutate(year = as.double(str_sub(`DATE`, 0, 4)), construction = as.double(str_remove(`TLPBLCONS`, ","))) |>
  filter(year >= 1998 & year < 2021) |>
  select(year, construction)


limedata <- read.csv("data/lime.csv") |>
  mutate(year = as.double(Year), lime = as.double(str_remove(`Lime`, ","))) |>
  select(year, lime)

setwd("~/Desktop/Rdata-science/cementresearch")
silicadata <- read.csv("data/silica.csv") |>
  mutate(year = as.double(Year), silica = as.double(str_remove(`Silica`, ","))) |>
  select(year, silica)


gasdata <- read.csv("data/gasppi.csv") |>
  mutate(year = as.double(str_sub(`DATE`, 0, 4)), gasppi = as.double(str_remove(`WPU0531`, ","))) |>
  select(year, gasppi) |>
  filter(year >= 1998 & year < 2021) 


petrodata <- read.csv("data/petrodata.csv") |>
  mutate(year = as.double(str_sub(`DATE`, 0, 4)), petrocoal = as.double(str_remove(`WPU058103`, ","))) |>
  filter(year >= 1998 & year < 2021) |>
  select(year, petrocoal)

setwd("~/Desktop/Rdata-science/cementresearch")
workersdata <- read.csv("data/workers.csv") |>
  mutate(year = as.double(str_sub(`DATE`, 0, 4)), workers = as.double(str_remove(`USCONS`, ","))) |>
  filter(year >= 1998 & year < 2021) |>
  select(year, workers)


combinedata <- bind_cols(c(datacpi, dataunemploy, datagdp, dataoil, 
                           datacement, popdata, cementprod, cementclinker, 
                           housingcomplete, constructspending, limedata, 
                           gasdata, petrodata, workersdata, silicadata)) |>
  mutate(name = `Country Name...1`, year = `years...2`) |>
  select(name, year, cpi, unemploy, gdp, oilprice, 
         cementppi, population, concreteid, Cement, 
         Clinker, housing, construction, lime, gasppi,
         petrocoal, workers, silica)
setwd("~/Desktop/Rdata-science/cementresearch")
write_csv(combinedata, "combinedata.csv")

```

```{r}
flexplot(concreteid~cpi + unemploy, data=combinedata, method="lm")
```


```{r}


cordata <- combinedata |>
  mutate(year = as.double(year)) |>
  select(!c(name,year)) 

cordata2 <- combinedata |>
  mutate(year = as.double(year)) |>
  mutate(unemploy = log10(unemploy), gdp = log10(gdp), oilprice = log10(oilprice), cementppi = log10(cementppi), population = log10(population), concreteid = log10(concreteid), Cement = log10(Cement),
         Clinker = log10(Clinker)) |>
  select(!c(name,year)) 

cormatrix <- rcorr(as.matrix(cordata))

cormatrix$r


```

```{r warning=FALSE}
chart.Correlation(cordata, histogram=TRUE, pch="+")

chart.Correlation(cordata2, histogram=TRUE, pch="+")
```

```{r}
mod_gam1 <- gam(concreteid ~ cpi + s(unemploy) + s(oilprice) + s(gdp) + s(population) + s(cementppi), data = cordata)

summary(mod_gam1)



mod_lm1 <- lm(concreteid ~ year + cpi + unemploy + oilprice + gdp + population + cementppi, data = combinedata)

summary(mod_lm1)

mod_stan_glm1 <- stan_glm(concreteid ~ year + cpi + unemploy + oilprice + gdp + population + cementppi, data = combinedata, refresh = FALSE, iter = 5000)


# Predict concreteid for the year 2050
predicted_concreteid <- predict(mod_stan_glm1, newdata = new_data)

# View the predicted concreteid for the year 2050
print(predicted_concreteid)

summary(mod_stan_glm1)
```


```{r}
better_corr = function (data, mapping, alignPercent = 0.6, method = "pearson",
                        use = "complete.obs", corAlignPercent = NULL, corMethod = NULL,
                        corUse = NULL, ...)
{
  # for now this is just ggally_cor but gets rid of the ridiculous gridlines and "Corr:"
  require(GGally)
  if (!is.null(corAlignPercent)) {
    stop("'corAlignPercent' is deprecated.  Please use argument 'alignPercent'")
  }
  if (!is.null(corMethod)) {
    stop("'corMethod' is deprecated.  Please use argument 'method'")
  }
  if (!is.null(corUse)) {
    stop("'corUse' is deprecated.  Please use argument 'use'")
  }
  useOptions <- c("all.obs", "complete.obs", "pairwise.complete.obs",
                  "everything", "na.or.complete")
  use <- pmatch(use, useOptions)
  if (is.na(use)) {
    warning("correlation 'use' not found.  Using default value of 'all.obs'")
    use <- useOptions[1]
  }
  else {
    use <- useOptions[use]
  }
  cor_fn <- function(x, y) {
    cor(x, y, method = method, use = use)
  }
  xCol <- deparse(mapping$x)
  yCol <- deparse(mapping$y)
  if (GGally:::is_date(data[[xCol]]) || GGally:::is_date(data[[yCol]])) {
    if (!identical(class(data), "data.frame")) {
      data <- fix_data(data)
    }
    for (col in c(xCol, yCol)) {
      if (GGally:::is_date(data[[col]])) {
        data[[col]] <- as.numeric(data[[col]])
      }
    }
  }
  if (is.numeric(GGally:::eval_data_col(data, mapping$colour))) {
    stop("ggally_cor: mapping color column must be categorical, not numeric")
  }
  colorCol <- deparse(mapping$colour)
  singleColorCol <- ifelse(is.null(colorCol), NULL, paste(colorCol, collapse = ""))
  if (use %in% c("complete.obs", "pairwise.complete.obs", "na.or.complete")) {
    if (length(colorCol) > 0) {
      if (singleColorCol %in% colnames(data)) {
        rows <- complete.cases(data[c(xCol, yCol, colorCol)])
      }
      else {
        rows <- complete.cases(data[c(xCol, yCol)])
      }
    }
    else {
      rows <- complete.cases(data[c(xCol, yCol)])
    }
    if (any(!rows)) {
      total <- sum(!rows)
      if (total > 1) {
        warning("Removed ", total, " rows containing missing values")
      }
      else if (total == 1) {
        warning("Removing 1 row that contained a missing value")
      }
    }
    data <- data[rows, ]
  }
  xVal <- data[[xCol]]
  yVal <- data[[yCol]]
  if (length(names(mapping)) > 0) {
    for (i in length(names(mapping)):1) {
      tmp_map_val <- deparse(mapping[names(mapping)[i]][[1]])
      if (tmp_map_val[length(tmp_map_val)] %in% colnames(data))
        mapping[[names(mapping)[i]]] <- NULL
      if (length(names(mapping)) < 1) {
        mapping <- NULL
        break
      }
    }
  }
  if (length(colorCol) < 1) {
    colorCol <- "ggally_NO_EXIST"
  }
  if ((singleColorCol != "ggally_NO_EXIST") && (singleColorCol %in%
                                                colnames(data))) {
    cord <- ddply(data, c(colorCol), function(x) {
      cor_fn(x[[xCol]], x[[yCol]])
    })
    colnames(cord)[2] <- "ggally_cor"
    cord$ggally_cor <- signif(as.numeric(cord$ggally_cor),
                              3)
    lev <- levels(data[[colorCol]])
    ord <- rep(-1, nrow(cord))
    for (i in 1:nrow(cord)) {
      for (j in seq_along(lev)) {
        if (identical(as.character(cord[i, colorCol]),
                      as.character(lev[j]))) {
          ord[i] <- j
        }
      }
    }
    cord <- cord[order(ord[ord >= 0]), ]
    cord$label <- str_c(cord[[colorCol]], ": ", cord$ggally_cor)
    xmin <- min(xVal, na.rm = TRUE)
    xmax <- max(xVal, na.rm = TRUE)
    xrange <- c(xmin - 0.01 * (xmax - xmin), xmax + 0.01 *
                  (xmax - xmin))
    ymin <- min(yVal, na.rm = TRUE)
    ymax <- max(yVal, na.rm = TRUE)
    yrange <- c(ymin - 0.01 * (ymax - ymin), ymax + 0.01 *
                  (ymax - ymin))
    p <- ggally_text(label = str_c("Cor : ", signif(cor_fn(xVal,
                                                           yVal), 3)), mapping = mapping, xP = 0.5, yP = 0.9,
                     xrange = xrange, yrange = yrange, color = "black",
                     ...) + theme(legend.position = "none")
    xPos <- rep(alignPercent, nrow(cord)) * diff(xrange) +
      min(xrange, na.rm = TRUE)
    yPos <- seq(from = 0.9, to = 0.2, length.out = nrow(cord) +
                  1)
    yPos <- yPos * diff(yrange) + min(yrange, na.rm = TRUE)
    yPos <- yPos[-1]
    cordf <- data.frame(xPos = xPos, yPos = yPos, labelp = cord$label)
    cordf$labelp <- factor(cordf$labelp, levels = cordf$labelp)
    p <- p +
      geom_text(data = cordf, aes(x = xPos, y = yPos, label = labelp, color = labelp), hjust = 1, ...) +
      theme(legend.position = "none",
            panel.grid.major = element_blank())

    p
  }
  else {
    xmin <- min(xVal, na.rm = TRUE)
    xmax <- max(xVal, na.rm = TRUE)
    xrange <- c(xmin - 0.01 * (xmax - xmin), xmax + 0.01 * (xmax - xmin))
    ymin <- min(yVal, na.rm = TRUE)
    ymax <- max(yVal, na.rm = TRUE)
    yrange <- c(ymin - 0.01 * (ymax - ymin), ymax + 0.01 * (ymax - ymin))
    cval = cor_fn(xVal, yVal)
    p <- ggally_text(label = paste(signif(cval, 3), sep = "", collapse = ""),
                     mapping,
                     xP = 0.5,
                     color=I(ifelse(cval>0,
                                    scales::alpha(scales::muted("blue"), alpha=abs(cval)),
                                    scales::alpha(scales::muted("red"), alpha=abs(cval)))),
                     yP = 0.5,
                     xrange = xrange,
                     yrange = yrange, ...) +
      theme(legend.position = "none",
            panel.grid.major = element_blank())
    p
  }
}
```

```{r}
better_smooth <- function(data, mapping, ptcol, ptalpha=1, ptsize=1, linecol, ...) {
  p <- ggplot(data = data, mapping = mapping) +
    geom_point(color=ptcol, alpha=ptalpha, size=ptsize) +
    geom_smooth(color=linecol, ...)
  p
}
```


```{r message=FALSE}
p = GGally::ggpairs(
  cordata[, c(1, 2:9)],
  lower = list(
    continuous = GGally::wrap(
      better_smooth,
      ptalpha = .25,
      ptcol = '#D55E00',
      ptsize = 1,
      linecol = '#03b3ff',
      method = 'loess',
      se = F,
      lwd = .5
    )
  ),
  diag = list(continuous = GGally::wrap(
    'densityDiag', color = 'red', lwd = .5
  )),
  # upper=list(continuous=GGally::wrap(better_corr)),
  axisLabels = "none"
)

p
```


```{r}
datagdp |>
  ggplot(aes(x = years, y = gdp)) + 
  geom_point() + 
  scale_y_log10()
```








