---
title: "yuhants"
author: "Yuhan"
date: "2023-07-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(forecast)
```

```{r}
combinedata

ts_data <- ts(combinedata[, c("cpi", "unemploy", "gdp", "oilprice", 
                              "cementprice", "population", "concreteppi", "Cement", "Clinker")], 
              start = combinedata$year[1], frequency = 1)

regressor_Cement <- ts(combinedata$Cement, start = combinedata$year[1], frequency = 1)

regressor_concreteppi <- stats::lag(ts(combinedata$concreteppi, start = combinedata$year[1], frequency = 1),1)
regressor_unemploy <- stats::lag(ts(combinedata$unemploy, start = combinedata$year[1], frequency = 1),1)
regressor_cementprice <- stats::lag(ts(combinedata$cementprice, start = combinedata$year[1], frequency = 1),1)
regressor_oilprice <- stats::lag(ts(combinedata$oilprice, start = combinedata$year[1], frequency = 1),1)


regressor_matrix <- cbind(regressor_concreteppi, 
                          regressor_unemploy, 
                          regressor_cementprice, 
                          regressor_oilprice)


  # Replace with appropriate ARIMA(p, d, q) order based on model selection
fit <-  Arima(regressor_Cement, xreg = regressor_matrix)

horizon <- 100  # Replace with the number of steps you want to forecast ahead
fut_concreteppi <- forecast(regressor_concreteppi, h = horizon)
fut_unemploy <- forecast(regressor_unemploy, h = horizon)
fut_cementprice <- forecast(regressor_cementprice, h = horizon)
fut_oilprice <- forecast(regressor_oilprice, h = horizon)

# Combine future regressors into a matrix with the same number of columns as regressor_matrix
newxreg <- cbind(fut_concreteppi$mean, 
                 fut_unemploy$mean, 
                 fut_cementprice$mean, 
                 fut_oilprice$mean)

# Generate future forecasts using ARIMA model and newxreg
forecast_result <- forecast(fit, xreg=newxreg)

plot(forecast_result)

```

```{r}

modelpred <- lm(Cement ~ cpi + unemploy + oilprice  + log(cementprice) + log(concreteppi), 
                data = combinedata)

modelpred2 <- lm(log(Cement) ~ log(cpi) + log(unemploy) + log(oilprice)  + log(cementprice) + log(concreteppi), 
                data = combinedata)
  
summary(modelpred)
summary(modelpred2)
```




```{r}
# Function to perform linear regression and check for multiplicative/additive relationship
check_relationship <- function(x, y) {
  additive_model <- lm(y ~ x)
  multiplicative_model <- lm(log(y) ~ log(x))
  
  return(list(
    additive = summary(additive_model),
    multiplicative = summary(multiplicative_model)
  ))
}

# Apply the function to each variable
results_x1 <- check_relationship(combinedata$cpi, combinedata$Cement)
results_x2 <- check_relationship(combinedata$unemploy, combinedata$Cement)
results_x3 <- check_relationship(combinedata$gdp, combinedata$Cement)
results_x4 <- check_relationship(combinedata$oilprice, combinedata$Cement)
results_x5 <- check_relationship(combinedata$cementprice, combinedata$Cement)
results_x6 <- check_relationship(combinedata$population, combinedata$Cement)
results_x7 <- check_relationship(combinedata$concreteppi, combinedata$Cement)
results_x8 <- check_relationship(combinedata$Clinker, combinedata$Cement)

# Function to print results
print_results <- function(var_name, results) {
  cat("Variable:", var_name, "\n")
  cat("Additive Model:\n")
  print(results$additive)
  cat("Multiplicative Model:\n")
  print(results$multiplicative)
  cat("\n")
}

# Print the results
print_results("x1", results_x1) # cpi

print_results("x2", results_x2) # unemploy

print_results("x3", results_x3) # gdp

print_results("x4", results_x4) # oilprice

print_results("x5", results_x5) # cementprice

print_results("x6", results_x6) # population

print_results("x7", results_x7) # concreteppi

print_results("x8", results_x8) # Clinker



```

